#! /usr/bin/env python


"""SpringLeaf - SpringBoot CLI

Usage:
  springleaf init
  springleaf generate
  springleaf new <name>
  springleaf (-h | --help)

Options:
  -h --help     Shows help
  init          Inits a new SpringLeaf CLI
  generate      Starts a generator CLI
  new <name>    Creates a new SpringBoot Project with given name

"""


from docopt import docopt

from springleaf.cli import CLI

"""
Author: Omar Iriskic
@contact:
    https://omaririskic.com/
    https://github.com/OMKE
"""

if __name__ == "__main__":
    args = docopt(__doc__)
    CLI(args)
